using Landoria.WorldCrawler.Capture;

namespace Landoria.WorldCrawler.Restoration.Objects
{
    // Excludes engine-owned records that must be regenerated by the destination world.
    internal static class RestoreRecordPolicy
    {
        // Keeps terrain changes but never replaces Valheim's live per-zone controller.
        internal static bool Include(CapturedObject source)
        {
            return source != null && source.PrefabName != "_ZoneCtrl";
        }
    }
}
